apiVersion: v1
kind: Pod
metadata:
  name: alpr-api
spec:
  restartPolicy: OnFailure
  containers:
    - name: alpr-api
      image: "stash1001/alpr-api"
      resources:
        limits:
          nvidia.com/gpu: 1